Dro beta work with WCS for XYZ and MCS for ABC
Really not perfect but i need to understand better for 

UnboundLocalError: local variable 'data' referenced before assignment

for now many time the X Dro show A value
Dro not reset to 0 when disconnect host